# Generated by Django 5.0.1 on 2024-01-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrantes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('localizacion', models.PositiveIntegerField(unique=True)),
                ('localizaciony', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('idenfermedad', models.PositiveIntegerField()),
                ('enfermedad', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('codigo', models.PositiveIntegerField()),
                ('especies', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('municipios', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('provincias', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('sector', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Densidades',
            fields=[
                ('categorias', models.CharField(max_length=20)),
                ('idencidad', models.AutoField(primary_key=True, serialize=False)),
                ('cantidades', models.PositiveIntegerField(blank=True, null=True)),
                ('cuadrantes_localizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='densidades_cuadrantes_localizacion_set', to='tasks.cuadrantes')),
                ('cuadrantes_localizaciony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.cuadrantes')),
                ('especies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.especies')),
            ],
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('propietarios', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('provincias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias')),
                ('sectores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sectores')),
            ],
        ),
        migrations.CreateModel(
            name='NotiDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('No_orden', models.IntegerField()),
                ('unidad', models.CharField(max_length=50)),
                ('cuadrante', models.IntegerField()),
                ('codigo_entidad', models.IntegerField()),
                ('codigo_especialista', models.IntegerField()),
                ('poblacion', models.IntegerField()),
                ('enfermos', models.IntegerField()),
                ('muertos', models.IntegerField()),
                ('sac', models.IntegerField()),
                ('fecha_envio', models.DateField()),
                ('fecha_confeccion', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('parte', models.TextField()),
                ('municipio', models.ForeignKey(db_column='municipios', on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('propietario', models.ForeignKey(db_column='propietarios', on_delete=django.db.models.deletion.CASCADE, to='tasks.propietarios')),
            ],
        ),
        migrations.CreateModel(
            name='FuentesCalculos',
            fields=[
                ('codigo_fuentes_calculo', models.AutoField(primary_key=True, serialize=False)),
                ('fechas_ocurrencias', models.DateField(blank=True, null=True)),
                ('fechas_cierres', models.DateField(blank=True, null=True)),
                ('fechas_confirmaciones', models.DateField(blank=True, null=True)),
                ('cantidad_recuperados', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_muertos', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_enfermos', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_totales', models.PositiveIntegerField(blank=True, null=True)),
                ('cuadrantes_localizacion', models.ForeignKey(db_column='cuadrantes_localizacion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fuentescalculos_cuadrantes_localizacion_set', to='tasks.cuadrantes')),
                ('cuadrantes_localizaciony', models.ForeignKey(db_column='cuadrantes_localizaciony', on_delete=django.db.models.deletion.CASCADE, to='tasks.cuadrantes', to_field='localizaciony')),
                ('idenfermedades', models.ForeignKey(db_column='idEnfermedades', on_delete=django.db.models.deletion.CASCADE, to='tasks.enfermedades')),
                ('municipios', models.ForeignKey(db_column='municipios', on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('propietarios', models.ForeignKey(db_column='propietarios', on_delete=django.db.models.deletion.CASCADE, to='tasks.propietarios')),
            ],
        ),
        migrations.AddField(
            model_name='municipios',
            name='provincias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias'),
        ),
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapas', models.CharField(max_length=20)),
                ('provincias', models.ForeignKey(db_column='provincias', on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_areas', models.CharField(max_length=20)),
                ('areas_localizacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='areas_cuadrantes_localizacion_set', to='tasks.cuadrantes')),
                ('areas_localizaciony', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='areas_cuadrantes_localizaciony_set', to='tasks.cuadrantes')),
                ('provincias_codigos_provincias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='Subareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_subareas', models.CharField(max_length=20)),
                ('areas_cuadrantes_localizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subareas_areas_cuadrantes_localizacion_set', to='tasks.areas')),
                ('areas_cuadrantes_localizaciony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas_cuadrantes_localizaciony_set', to='tasks.areas')),
                ('areas_nombres_areas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subareas_areas_nombres_areas_set', to='tasks.areas')),
                ('cuadrantes_localizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas_localizacion_set', to='tasks.cuadrantes')),
                ('cuadrantes_localizaciony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas_localizaciony_set', to='tasks.cuadrantes')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSectores',
            fields=[
                ('tipoSector', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sectores')),
            ],
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('especie', models.ForeignKey(db_column='especies', on_delete=django.db.models.deletion.CASCADE, to='tasks.especies')),
                ('municipio', models.ForeignKey(db_column='municipios', on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('propietario', models.ForeignKey(db_column='propietario', on_delete=django.db.models.deletion.CASCADE, to='tasks.propietarios')),
                ('provincia', models.ForeignKey(db_column='provincias', on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias')),
                ('sector', models.ForeignKey(db_column='sectores', on_delete=django.db.models.deletion.CASCADE, to='tasks.sectores')),
                ('tipoSector', models.ForeignKey(db_column='tipoSector', on_delete=django.db.models.deletion.CASCADE, to='tasks.tiposectores')),
            ],
        ),
        migrations.CreateModel(
            name='Traslados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas_salidas', models.DateField()),
                ('cantidades', models.PositiveIntegerField(blank=True, null=True)),
                ('cuadrantes_localizacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_cuadrantes_localizacion_destino_set', to='tasks.cuadrantes')),
                ('cuadrantes_localizacion_procedencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_cuadrantes_localizacion_procedencia_set', to='tasks.cuadrantes')),
                ('cuadrantes_localizacionm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.cuadrantes')),
                ('cuadrantes_localizaciony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_cuadrantes_localizaciony_set', to='tasks.cuadrantes')),
                ('especies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.especies')),
                ('municipios_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('municipios_procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_municipios_procedencia_set', to='tasks.municipios')),
                ('nombres_propietarios_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.propietarios')),
                ('nombres_propietarios_procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_nombres_propietarios_procedencia_set', to='tasks.propietarios')),
            ],
        ),
    ]
