# Generated by Django 5.0.2 on 2024-04-26 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_subareas_areas_cuadrantes_localizaciony_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipoAnimal', models.CharField(max_length=50)),
                ('investigaciones', models.CharField(max_length=500)),
                ('provinciaDestino', models.CharField(max_length=50)),
                ('municipioDestino', models.CharField(max_length=50)),
                ('propietarioDestino', models.CharField(max_length=50)),
                ('solicita', models.CharField(max_length=100)),
                ('tramita', models.CharField(max_length=100)),
                ('autoriza', models.CharField(max_length=100)),
                ('nacion', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.propietarios')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias')),
            ],
        ),
    ]
