# Generated by Django 5.0.2 on 2024-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_traslado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traslado',
            name='investigaciones',
            field=models.TextField(max_length=500),
        ),
    ]
