# Generated by Django 5.0.4 on 2024-04-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_parte_notidiaria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notidiaria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notidiaria',
            name='enfermos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notidiaria',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notidiaria',
            name='fecha_confirmacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notidiaria',
            name='muertos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notidiaria',
            name='poblacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notidiaria',
            name='sacrificados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('municipio_uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_uni', to='tasks.municipios')),
                ('provincia_uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_uni', to='tasks.provincias')),
            ],
        ),
        migrations.AlterField(
            model_name='notidiaria',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.unidad'),
        ),
    ]
