# Generated by Django 5.0.4 on 2024-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_notidiaria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
